tableprefix : ''
config:
    driver        : pdo_mysql
    host          : localhost
    user          : hist
    password      : hist
    dbname        : hist
    charset       : utf8
    driverOptions :
        1002 : 'SET NAMES utf8'
