tableprefix : ''
config:
    driver        : pdo_mysql
    host          : localhost
    user          : hotel
    password      : hotel
    dbname        : hotel
    charset       : utf8
    driverOptions :
        1002 : 'SET NAMES utf8'
